apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
  annotations:
    kubernetes-engine.cloud.google.com/icon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJYAAACWCAYAAAA8AXHiAAAAAXNSR0IArs4c6QAADdlJREFUeAHtnQ9wVEcdx3ffXZILUKHU/qHttIBObeuUqlCntGADl/Avf6AoaK3jYAWq4x8UC7lA1dhiLgkInaodLdoZ61RoaumQPyD5A7RjW6cWx6LFShWKAlKwpC0M5MjdW7+b5rBA7u7t3nvJvtzvDcfdvd3fvt3PfrP723277xijgwgQASJABIgAESACRIAIEAEiQASIABEgAkSACBABIkAEiAARIAJEgAgQASJABIgAESACRIAIEAEiQASIABEgAkSACBABIkAEiAARIAI5RIBnKmtJU63IFIfCc5NAW3kkpX6s3ERCpfaaAAnLa8I5mj4JK0cr3utik7C8Jpyj6ZOwcrTivS52UPcC6UYEummSnZkEdGYGqMUysy59nysSlu+r0MwCkLDMrBff54qE5fsqNLMAJCwz68X3uSJh+b4KzSwACcvMevF9rkhYvq9CMwtAwjKzXnyfKxKW76vQzAKQsMysF9/nioTl+yo0swAkLDPrxfe5ImH5vgrNLAAJy8x68X2uSFi+r0IzC0DCMrNefJ8rEpbvq9DMApCwzKwX3+dKe827iSUv2lEdyns3f7xt8as5t0YxwYYzZvexW5d3Mc73WiKx58ywM//YOaU6bmJ5/JwnXwur6Jl1I/ICXTPxDIBJEMqt/AS7mVks0NMMi+STAfrQlawxhAtEDp4MdWOzwB7EfoUz8SLPD25qnb7sqJ8r1YS8+1JYU1tqP2XZYjEXXfMgqPyz0jn7wTlamOQh9s14v5kx/kX7TOKR4qba7cLmdR2zK9ucp0Qx30/AV8IqaambwGyxntnsYxBBz7/3F8aNz72phrklwiWN0efjjN+7oyLyarq0S5qj85jgDenipAtD29klbHt0x+yVb6aL56cwXzjvM7c8XIDu6iFhi5cAF6Lqp4Pz24NM7C5ujK5Kd8W2sqqn0JV2pIuTLowzHuKWVZ0ujt/CjBdWcVvt8O7EqRcAdok3bVSGKsMogHO+Et3jY/MaGgIpY3OxGOLqThmeIYALvqhoS93VGaL5JthoYU1sWFuI8VsrBPWJgSaKPHyps3Df5lT5aC+r2ocBwdpU4RnPcxYIxu2ajPF8EsFoYQ0rPPM4OH7SFJYQVyn8rgWp8tPJYw9guPmfVOGZziP9u6c11VyfKZ4fwo0VVnFzdDEAfsY8iLxu2rbVQ/vK167y6lMYUyzpK8zROXS7tuBp/TlH6RgQyUhhyS4Q85prsucjTmGy6jn4Pr/H653s00MKnF0mziS+liqtrB15zj8d3vzDcanS98t5I6cbhhR2LeLMuigLiK+jS6rvHhbbiFn1kz3pCMHDW6M38LgVZlzchZHYRN30hRB3w7Y+pb105AV/DV2bnCNTPtBw1cFoprKhQQZGtlgYIS3QZWQzsWLE6bE3tJVX/eKsqGRinIuOWSv2tFdEftxeXnUbzmg72hgljks3gpOOPES1TrcMSH9GuDF6i669CXbGCauopf4KgP24DhzcpdnUUV4VfWr+/EQmezzf6zsYxW3IFC9VeMBm4VRh8vxx1vWDrBx5zrWFny5f/RVmnLDyEokpuoW3OZddiOODs+BKx5HPi2gJ+6bzTp3zVTry6A6/dc5JhS9o8SaVNEWnKZgYFdU4YQnOb9QhhNsi8e1ly/+oYttasWw/7Paq2CTjYjCQcTIT3W4DWsXnkzaq72iBV6vamBLfOGFxwUZpwRH8tPSj1G35HnUbacFHOLFDlhYiU1oz8tKXQ6t1p5PrmBbHOGEBUIEOJM7ZRUVNaz6obiuOq9v0WDjKZ2v5itfgaz2keQ1pVsNEtYn1lLZIxk03oGs6hqmAtJlOFRgU8QUIU5r/wgjxy7CRL8+OTharHskKvoBWTqM15teHmwvuwh3uJzzLoAcJG/eXAB/roG450WpVTWmqxboqsw7pyNuMfVs3V/gzeyDtDXDdhD20M05Y8JK0hQVOIwNMvIyVCNHxTdVDPOSmnDSmQZ7UdeTRgo/FDfB7lC86gAbGCSsh+CvZ8EAlBPEXHhnJQkeLG2ufhsgW4XVNNmm6ZZuNIw9RPjj+5Z9rzeS7lX+VdIwT1o7ZlX9HAf6sUogUcYeia5wLkT2K14GSxtp9GGGtDzfXfm7ylppLU9h4ejobRx4jxMsvPvJ2ynuUnmZcI3HjhCXLgHtxj2uUJb0JZ2PgPC+0BNsQSlhH0YrtlqtSpzXVlmN3z7D0xu6FSkdee0betu9PtbLCvRy6k5KRwgrkF/wK8I+5U8S+U0ErJmfOl2COqTF4sqAT66x2QmjLi1tq086o952a87PZOPJotS4R3Qn9ZTnOs5l1TCOFtW3GUjm3hOF5/xzSL8Pk6h24Wh232e7ipuhBtGiPhJtrJnuRg2wceWGzZdN/t3akF/lyM00jhSULiNUJrWi1fuRmYZ2mBaFdhRbtq5awnkNL9jp8s4VObZ3Gk4481oplvFl+fnrwG0ckumOR88+b9t1YYUlQbWWRZfC3fj2g0Dj/MHyz9WjBdhRtjY52Ky/SkUc3rLu05htTm1Zd5VZevEjHaGHJe3/t5bEFPS2XQCcwgAdasKJgN99d0lgvu0xXjk7e9X0dRx4taggbvh9wJRMeJWK2sGShebWNbvE+bBwdpzvB6BY7dEMXCW63hZvqXFmL3+PIc75UJ3+YSF4Qbqm5Tse2P2zMF1YvBbkbua2iahITVhH+yrfgdKw3qF/f0HLlYS3WE1O31H/IjQt3lEU2av3ByP2Ods8SZjey4XoavhFWsuRtFcufRQtWGgwMGW7bXC6E+ymc4DeS4f3yjudFWPHEBrdWHWg78ozNmdYcHd8vZVa8iO+ElSzf1lnfjMmHdmCJ8dfbKiJjuAiMxdYpjLSw3Fiwo8l4Xr1jTumWcHPhXDfSz8aRxyrVh93Ig9tpBN1OcKDSk6tBce1f9r5YeEvNje/tyGFTcW4KurDhbueNCzEPaf7WjXSlI4+lNdj9o7y05rbi5trS9rJIixv5cCsN37ZYmQD8f0dO5M72sq6RzOJy10ulYGwbfLRTmewdhpf37IF0GDldtGwcebTSa93qltPlUSVs0ArrHAhyZFla+TK6zfr28siMYGDoSMyPYWTXMwg4J6rKF4wSC4eGul1b/6XryGP64bri5lC/3alwwig3hHUeCemftVdUPS0HATYX3zsvWOmr4OwKJYMMkfGUwfsyREkRLGpMWlZjlI81rXH1GJvHr01BLvVpi7/VXhr5S+oIqUM6yqoexC0b3Hjm0l9SPjCi01hunPoycWH/Nw9Noeohb0N94HCnnNd6VdXWi/hGCctm8c8D0CrVgmJOfgdspJOudWD39DpLU1jwby7XuuggNzKqK4Rj3anDG7PQo3XskjaB/Lx/Jj+rv/O4us3gtzBKWGitDmkhxyI+va1f713tTMLO17puj5F4W9928FoaJSwRsP+mizqPdc/Rtk3YWruv5fXwCO99utcdzHZGCaujdMVedIfv6AAXjH83iyXGX9G5prTBKO6vuraD2c4oYfWClo648oFx1DV5J0INH22oVurWwk3Rz6Ld0dvGjnuUmBf7l3Jmc8DARGE9o82ds5mjQiFskqgLZ0pD7jvEEuR6+HXajzLCru0nM10nV8ONmm6QlRAf1vWb4IlQFFM5V+pUCuw+gg6qHaI5APsGPLHlDbRmb8IZekumh/BL8bD/O3D+bnweoXONHhssPIwHrZ9o2w9yQ+OEJX8wCcuAq8H90WzYoyW6FvbLIJ5zDzhx8rjg/HunHf+PGfcNO2dVHnRskGMRTewK2cWnxz6GenBj06pX1XlcdIslXiU+GNI1UljyUY88Ea9Al+bp3kKdCoRf1ZVgfGbH3BU9XatOGrlgY6SwJPjWOff/27btYt3pB48qLyZsq2J7eeVLHqU/aJI1VliSMH4Nazcc7RloudxaP6VdcWipDiQ4m0o/NecModHCkkVor6j8QyIQGAdx6U9DOGPRZyy0mBhAip+dtq2btpdFXugzEp28gIBxo8ILcogT22ctlzeJ55ZsrrldcGsNRnS39hXPzXMQUxyt5SbLEvWtZVW73Ew7F9LyhbCSFdE2e4V8AvFEucYbP4Z5DwQ2Hd+HJsPdeMfK0j3CYhsTPLB+Z+nyI26kmYtp+EpYyQrq3TjQIldMXnL4+GQ8XnICeqwJuF8o9/pdiU0Ol2GiKn03jwlOxD+Cnz85gDmvP+H9WZ4XfLaNfg86iTmrd18KK1niXRPulY+53t77Sp5m8nmdx4btHxWM41ns3A6dDcAHdHExYeUftoecPGTir9fHYgWHgoWxKe/Ps9PP7/LYfqdxvY7na2GlgtP7kycHES5fvjpenL/0NDK801eZ7iOz6buLPgzoFBFwQoCE5YQSxVEmQMJSRkYGTgiQsJxQojjKBEhYysjIwAkBEpYTShRHmQAJSxkZGTghQMJyQoniKBMgYSkjIwMnBEhYTihRHGUCJCxlZGTghAAJywkliqNMgISljIwMnBAgYTmhRHGUCZCwlJGRgRMCJCwnlCiOMgESljIyMnBCgITlhBLFUSZAwlJGRgZOCJCwnFCiOMoEtDdT4Ie5ex8IpHxNMsgBAtRi5UAlD0QRSVgDQT0HrknCyoFKHogikrAGgnoOXJOElQOVTEUkAkSACBABIkAEiAARIAJEgAgQASJABIgAESACRIAIEAEiQASIABEgAkSACBABIkAEiAARIAJEgAgQASJABIgAESACRIAIEAEiQASIABHwmMD/ACLri+QrCDdEAAAAAElFTkSuQmCC
    marketplace.cloud.google.com/deploy-info: '{"partner_id": "syntasa-public", "product_id": "syntasa", "partner_name": "Syntasa"}'
spec:
  descriptor:
    type: Syntasa
    version: '1.0'
    maintainers:
      - name: SYNTASA
        url: https://www.syntasa.com
    keywords:
      - "machine learning"
      - "data analytics"
      - "data preparation"
      - "data processing"
      - "kubernetes"
      - "syntasa"
      - "k8s"
    description: |-
      The Syntasa platform enables digital teams to ingest their first-party digital data, combine it with their
      internal customer data at the individual level, build custom AI/ML models, and activate them across digital channels.
      Our self-service web application enables digital teams to build the data pipelines, custom AI/ML models,
      and activations they need to deliver world-class digital experiences. Advanced users can use their preferred
      data science tools (like notebooks, R, and Python) to build their own models and easily put them into production
      with our platform. We offer pre-built adaptors to integrated with: martech systems like Adobe Analytics,
      Google Analytics 360, Adobe Target, Optimizely, Adobe Campaign, Marketo, Eloqua, and Salesforce; adtech systems
      like Adobe Audience Manager, Google Audience 360, Google Ad Center, Facebook Ads, Twitter Ads, LinkedIn Ads,
      DoubleClick Manager, Google Display & Video 360, and Nielsen; and cloud data platforms like BigQuery,
      RedShift, HD Insight, Snowflake, and Qubole.

      # Getting Started
      Please visit the following guide to get started:
      https://help.syntasa.com/hc/en-us/articles/360003406618-Syntasa-Introduction

      # Next Steps
      After Deploying the SYNTASA application in Google Marketplace on a GKE cluster, please visit the "Services and Ingresses"
      page and head towards the IP pointed to by the 'syntasa-ingress' service.  For more information please visit the
      following document on how to retrieve your SYNTASA application UI:

      https://github.com/syntasa-dev/syntasa-google-marketplace#accessing-the-syntasa-application-ui

      # Terms of Service
      Please refer to the SYNTASA licensing agreement

      # Support
      For support please reach out to support@syntasa.com
      Additionally please see the links below for any additional technical guidance.

    links:
      - description: SYNTASA Website
        url: "https://www.syntasa.com"
      - description: SYNTASA Prerequisites
        url: "https://github.com/syntasa-dev/syntasa-google-marketplace/blob/master/docs/PREREQUISITES.md"
      - description: SYNTASA Marketplace Documentation
        url: "https://github.com/syntasa-dev/syntasa-google-marketplace"
      - description: SYNTASA HELM On-Prem Deployment
        url: "https://github.com/syntasa-dev/syntasa-google-marketplace/blob/master/docs/HELM_INSTALLATION.md"
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ .Release.Name }}"
  info:
  - name: Syntasa Application Url
    type: Reference
    valueFrom:
      type: ServiceRef
      serviceRef:
        name: syntasa-ingress
        port: 443
        path: /
  componentKinds:
    - group: v1
      kind: Service
    - group: apps/v1
      kind: Deployment
    - group: v1
      kind: ConfigMap
    - group: v1
      kind: Secret
    - group: extensions/v1beta1
      kind: Ingress
    - group: v1
      kind: PersistentVolumeClaim